<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "poiz_csv_lister"
 *
 * Auto generated by Extension Builder 2017-10-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Poiz CSV Lister',
    'description' => 'An Extension for listing out the contents of a CSV File using Bootstrap...',
    'category' => 'plugin',
    'author' => 'Poiz Campbelll',
    'author_email' => 'p.campbell@complot.ch',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-9.4.10',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
